"""The attribution footer names the seats that reviewed (issue #911).

The markdown report already ended with an ai-jury footer. It now names the seats
that returned a review, is the one footer every posted comment ends with, and is
the thing `[jury.output] attribution = false` and `--no-attribution` remove. All
offline: `gh` is mocked and the panel runs via `--mock`.
"""

from __future__ import annotations

import contextlib
import io
import json
import sys
import tempfile
import unittest
import unittest.mock as mock
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from ai_jury import cli  # noqa: E402
from ai_jury.adapters import AgentResult  # noqa: E402
from ai_jury.config import ConfigError, _from_dict, validate_config  # noqa: E402
from ai_jury.incremental import parse_reviewed_sha  # noqa: E402
from ai_jury.report import render, render_footer, render_transcript  # noqa: E402

DIFF = """diff --git a/app.py b/app.py
index 0000000..1111111 100644
--- a/app.py
+++ b/app.py
@@ -1,2 +1,3 @@
 def f(x):
-    return x
+    return x + 1
"""

SHA = "c" * 40
REPO = "[ai-jury](https://github.com/berkayturanci/ai-jury)"
LEAD = f"<sub>🏛️ Synthesized by {REPO}"
TRANSCRIPT_LEAD = f"<sub>Generated by {REPO}"
MOCK_SEATS = f"{LEAD} · claude, codex — "

CONFIG = """
[jury]
rounds = 1
chair = "claude"

[jury.output]
attribution = {value}

[[agent]]
name = "claude"
vendor = "anthropic"
command = "claude"

[[agent]]
name = "codex"
vendor = "openai"
command = "codex"
"""


def _result(agent, ok=True, vendor="anthropic"):
    return AgentResult(agent=agent, vendor=vendor, ok=ok, output="x", duration_s=1.0)


def _run(args):
    out, err = io.StringIO(), io.StringIO()
    try:
        with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
            code = cli.main(args)
    except SystemExit as exc:
        code = exc.code
    return code, out.getvalue()


def _config_file(value: str) -> str:
    path = Path(tempfile.mkdtemp()) / "jury.toml"
    path.write_text(CONFIG.format(value=value), encoding="utf-8")
    return str(path)


@contextlib.contextmanager
def _gh(posted):
    record = lambda *a, **_k: posted.append(a[1])  # noqa: E731
    with (
        mock.patch("ai_jury.cli.pr_diff", return_value=DIFF),
        mock.patch("ai_jury.cli.pr_context", return_value="title"),
        mock.patch("ai_jury.cli.post_pr_comment", side_effect=record),
        mock.patch("ai_jury.cli.post_issue_comment", side_effect=record),
        mock.patch("ai_jury.cli.issue_body", return_value="# Bug\n\nIt breaks."),
        mock.patch("ai_jury.github.pr_head_sha", return_value=SHA),
    ):
        yield


def _seats(footer: str) -> str:
    """The seat list out of a summary footer, or "" when it names none."""
    head = footer.split(" — ", 1)[0]
    return head.split(" · ", 1)[1] if " · " in head else ""


class RenderFooter(unittest.TestCase):
    def test_names_the_seats_that_returned_a_review_in_seat_order(self):
        footer = render_footer([_result("claude"), _result("codex"), _result("agy")])
        self.assertTrue(footer.startswith(f"---\n\n{LEAD} · claude, codex, agy — "), footer)
        self.assertIn("[Add to your repo](https://ai-jury.dev/)</sub>", footer)

    def test_a_failed_seat_is_not_claimed(self):
        footer = render_footer([_result("claude"), _result("codex", ok=False)])
        self.assertEqual("claude", _seats(footer))

    def test_a_seat_that_reviewed_twice_is_named_once(self):
        # Chunked large-diff reviews carry one result per chunk per seat.
        footer = render_footer([_result("claude"), _result("codex"), _result("claude")])
        self.assertEqual("claude, codex", _seats(footer))

    def test_no_review_keeps_the_footer_without_a_seat_list(self):
        for reviews in ([_result("claude", ok=False)], [], [_result("")]):
            with self.subTest(reviews=reviews):
                footer = render_footer(reviews)
                self.assertIn(f"{LEAD} — Cross-vendor", footer)
                self.assertEqual("", _seats(footer))

    def test_a_name_cannot_break_out_of_the_line(self):
        footer = render_footer([_result("<b>x</b>\n## heading")])
        self.assertEqual("&lt;b&gt;x&lt;/b&gt; ## heading", _seats(footer))
        self.assertNotIn("\n## ", footer)  # no forged heading line

    def test_the_transcript_wording_names_the_seats_too(self):
        footer = render_footer([_result("claude")], transcript=True)
        self.assertIn(f"{TRANSCRIPT_LEAD} · claude — a cross-vendor", footer)

    def test_the_renderers_leave_it_off_when_asked(self):
        reviews = [_result("claude")]
        for fn in (render, render_transcript):
            with self.subTest(renderer=fn.__name__):
                self.assertIn("ai-jury](https", fn(reviews, [], None, chair="claude"))
                self.assertNotIn(
                    "ai-jury](https", fn(reviews, [], None, chair="claude", footer=False)
                )


class LocalReport(unittest.TestCase):
    def test_stdout_ends_with_exactly_one_footer(self):
        code, out = _run(["--mock", "-q"])
        self.assertEqual(0, code)
        self.assertEqual(1, out.count(LEAD))
        self.assertTrue(out.rstrip().endswith("</sub>"))
        self.assertIn(MOCK_SEATS, out)

    def test_the_footer_follows_the_ci_gate(self):
        # The CI gate is appended after rendering; the footer still closes the report.
        code, out = _run(["--mock", "-q", "--ci"])
        self.assertIn(code, (0, 1))
        self.assertLess(out.index("## CI gate"), out.index(LEAD))
        self.assertTrue(out.rstrip().endswith("</sub>"))

    def test_transcript_ends_with_its_one_footer(self):
        code, out = _run(["--mock", "-q", "--transcript"])
        self.assertEqual(0, code)
        self.assertEqual(1, out.count(TRANSCRIPT_LEAD))
        self.assertNotIn(LEAD, out)

    def test_no_attribution_removes_it_from_stdout(self):
        code, out = _run(["--mock", "-q", "--no-attribution"])
        self.assertEqual(0, code)
        self.assertNotIn("ai-jury](https", out)

    def test_json_never_gets_a_markdown_footer(self):
        code, out = _run(["--mock", "-q", "--format", "json"])
        self.assertEqual(0, code)
        json.loads(out)  # still one JSON document
        self.assertNotIn("<sub>", out)


class PostedComments(unittest.TestCase):
    def test_a_posted_summary_ends_with_one_footer_then_the_marker(self):
        posted = []
        with _gh(posted):
            code, _ = _run(["--mock", "--pr", "7", "--post", "-q"])
        self.assertEqual(0, code)
        body = posted[0]
        self.assertEqual(1, body.count(LEAD))
        self.assertIn(MOCK_SEATS, body)
        self.assertLess(body.index(LEAD), body.index("arc-reviewed-sha"))
        self.assertTrue(body.rstrip().endswith("-->"), "the SHA marker must stay last")
        # `--incremental` still reads the marker out of a comment carrying the footer.
        self.assertEqual(SHA, parse_reviewed_sha([body]))

    def test_no_attribution_flag_removes_it(self):
        posted = []
        with _gh(posted):
            code, _ = _run(["--mock", "--pr", "7", "--post", "--no-attribution", "-q"])
        self.assertEqual(0, code)
        self.assertNotIn("ai-jury](https", posted[0])
        self.assertEqual(SHA, parse_reviewed_sha(posted))

    def test_config_attribution_false_removes_it(self):
        posted = []
        with _gh(posted):
            code, _ = _run(
                ["--mock", "--pr", "7", "--post", "--config", _config_file("false"), "-q"]
            )
        self.assertEqual(0, code)
        self.assertNotIn("ai-jury](https", posted[0])

    def test_config_attribution_true_keeps_it(self):
        # Counterweight to the `false` case: the config file is read at all.
        posted = []
        with _gh(posted):
            code, _ = _run(
                ["--mock", "--pr", "7", "--post", "--config", _config_file("true"), "-q"]
            )
        self.assertEqual(0, code)
        self.assertIn(MOCK_SEATS, posted[0])

    def test_only_the_last_phased_comment_carries_it(self):
        posted = []
        with _gh(posted):
            code, _ = _run(["--mock", "--pr", "7", "--post", "--post-mode", "phased", "-q"])
        self.assertEqual(0, code)
        self.assertGreater(len(posted), 1)
        self.assertEqual([0] * (len(posted) - 1) + [1], [b.count(LEAD) for b in posted])
        self.assertLess(posted[-1].index(LEAD), posted[-1].index("arc-reviewed-sha"))
        self.assertEqual(SHA, parse_reviewed_sha(posted))

    def test_phased_honours_the_opt_out(self):
        posted = []
        with _gh(posted):
            code, _ = _run(
                ["--mock", "--pr", "7", "--post", "--post-mode", "phased", "--no-attribution"]
                + ["-q"]
            )
        self.assertEqual(0, code)
        self.assertFalse(any("ai-jury](https" in b for b in posted))

    def test_an_issue_comment_ends_with_one_footer(self):
        posted = []
        with _gh(posted):
            code, _ = _run(["--mock", "--issue", "5", "--post", "-q"])
        self.assertEqual(0, code)
        self.assertEqual(1, len(posted))
        self.assertEqual(1, posted[0].count(LEAD))
        self.assertTrue(posted[0].rstrip().endswith("</sub>"))

    def test_the_live_comment_carries_it_on_its_final_body_only(self):
        with (
            _gh([]),
            mock.patch("ai_jury.github.ProgressReporter") as reporter,
        ):
            code, _ = _run(["--mock", "--pr", "7", "--post-progress", "-q"])
        self.assertEqual(0, code)
        final = reporter.return_value.finish.call_args.args[0]
        self.assertEqual(1, final.count(LEAD))
        # The live comment's final body has never carried the incremental SHA
        # marker (only the summary, issue and phased paths add it), so it ends
        # with the footer; the docs say so rather than promising a marker.
        self.assertIsNone(parse_reviewed_sha([final]))
        self.assertTrue(final.rstrip().endswith("</sub>"))
        docs = (Path(__file__).parent.parent / "docs" / "configuration.md").read_text(
            encoding="utf-8"
        )
        self.assertIn("The `--post-progress`\nfinal body carries no SHA marker", docs)
        for call in reporter.return_value.update.call_args_list:
            self.assertNotIn("ai-jury](https", call.args[0])


class OutputConfigValidation(unittest.TestCase):
    @staticmethod
    def _with_output(body):
        return {
            "jury": {"rounds": 1, "chair": "a", "output": body},
            "agent": [{"name": "a", "vendor": "anthropic", "command": "claude"}],
        }

    def test_defaults_on(self):
        self.assertTrue(_from_dict(self._with_output({})).output.attribution)

    def test_false_turns_it_off(self):
        self.assertFalse(_from_dict(self._with_output({"attribution": False})).output.attribution)

    def test_a_non_bool_is_a_hard_error(self):
        # The string "false" is truthy; accepting it would keep the footer turned off.
        with self.assertRaises(ConfigError) as ctx:
            validate_config(self._with_output({"attribution": "false"}))
        self.assertIn("jury.output.attribution must be true or false", str(ctx.exception))

    def test_a_typo_warns_with_the_dotted_path(self):
        w = validate_config(self._with_output({"atribution": False}))
        self.assertEqual(1, len(w), w)
        self.assertIn("unknown key 'jury.output.atribution'", w[0])


if __name__ == "__main__":
    unittest.main()
