"""Render the council run into a single markdown report."""
from __future__ import annotations

from .adapters import AgentResult


def _block(title: str, body: str) -> str:
    return f"### {title}\n\n{body.strip() or '_(no output)_'}\n"


def render(
    reviews: list[AgentResult],
    debate: list[AgentResult],
    synthesis: AgentResult | None,
    *,
    chair: str,
) -> str:
    lines: list[str] = []
    lines.append("# 🏛️ Agent Review Council\n")

    panel = ", ".join(f"`{r.agent}` ({r.vendor})" for r in reviews)
    lines.append(f"**Panel:** {panel}\n")

    if synthesis and synthesis.ok:
        lines.append("## Chair verdict\n")
        lines.append(f"> Synthesized by `{chair}`\n")
        lines.append(synthesis.output.strip() + "\n")
    elif synthesis and not synthesis.ok:
        lines.append("## Chair verdict\n")
        lines.append(f"_Synthesis failed: {synthesis.error}_\n")

    lines.append("---\n")
    lines.append("## Round 1 — independent reviews\n")
    for r in reviews:
        status = f"{r.duration_s:.0f}s" if r.ok else f"⚠️ {r.error}"
        lines.append(_block(f"`{r.agent}` ({r.vendor}) — {status}", r.output if r.ok else ""))

    if debate:
        lines.append("## Round 2 — cross-examination\n")
        for r in debate:
            status = f"{r.duration_s:.0f}s" if r.ok else f"⚠️ {r.error}"
            lines.append(_block(f"`{r.agent}` — {status}", r.output if r.ok else ""))

    lines.append("---")
    lines.append(
        "\n<sub>Generated by "
        "[agent-review-council](https://github.com/berkayturanci/agent-review-council)"
        " — a cross-vendor multi-agent PR review council.</sub>"
    )
    return "\n".join(lines)
