"""Scaffold a ``council.toml`` from agent selections (issue #107).

Backs the ``council init`` command: instead of hand-editing TOML, a user (or a
script) picks agents/rounds/chair and this renders a valid config. The cloud
agent templates reuse the **secure-by-default** entries from
:data:`config.DEFAULT_CONFIG` (issue #100) so generated configs are safe; a
``local`` template targets an OpenAI-compatible server (Ollama by default).

Pure and deterministic: building the config dict and rendering it to TOML are
side-effect-free, so they are fully unit-testable; the CLI layer owns prompting,
availability detection, and writing the file.
"""
from __future__ import annotations

from .config import DEFAULT_CONFIG

_LOCAL_TEMPLATE = {
    "name": "qwen",
    "vendor": "local",
    "model": "qwen2.5-coder:7b",
    "endpoint": "http://localhost:11434/v1",
}


def _from_default(name: str) -> dict | None:
    for a in DEFAULT_CONFIG.get("agent", []):
        if a.get("name") == name:
            return dict(a)
    return None


def agent_templates() -> dict[str, dict]:
    """Built-in agent templates keyed by short name (a fresh copy each call)."""
    templates: dict[str, dict] = {}
    for name in ("claude", "codex", "agy"):
        tmpl = _from_default(name)
        if tmpl is not None:
            templates[name] = tmpl
    templates["qwen"] = dict(_LOCAL_TEMPLATE)
    return templates


KNOWN_AGENTS: tuple[str, ...] = ("claude", "codex", "agy", "qwen")

# Substrings that hint a local model is code-oriented (preferred for reviews).
_CODER_HINTS: tuple[str, ...] = ("coder", "code", "deepseek", "qwen")


def pick_default_model(models: list[str]) -> str | None:
    """Choose a sensible default from discovered local models (issue #109).

    Prefers a code-oriented model (name contains 'coder'/'code'/etc.), else the
    first listed; returns None for an empty list.
    """
    if not models:
        return None
    for m in models:
        low = m.lower()
        if any(h in low for h in _CODER_HINTS):
            return m
    return models[0]


def build_config(
    agents: list[str],
    *,
    rounds: int = 2,
    chair: str | None = None,
    verify: bool = True,
    local_model: str | None = None,
    local_endpoint: str | None = None,
) -> dict:
    """Build a council config dict from selected agent names.

    Raises ``ValueError`` on an unknown agent name or an empty selection. The
    chair defaults to the first selected agent. Local agents pick up the
    optional model/endpoint overrides.
    """
    templates = agent_templates()
    chosen: list[dict] = []
    seen: set[str] = set()
    for name in agents:
        if name in seen:
            continue
        tmpl = templates.get(name)
        if tmpl is None:
            raise ValueError(
                f"unknown agent '{name}'; choose from {', '.join(KNOWN_AGENTS)}"
            )
        entry = dict(tmpl)
        if entry.get("vendor") == "local":
            if local_model:
                entry["model"] = local_model
            if local_endpoint:
                entry["endpoint"] = local_endpoint
        chosen.append(entry)
        seen.add(name)

    if not chosen:
        raise ValueError("select at least one agent")

    if chair is None:
        chair = chosen[0]["name"]

    return {
        "council": {"rounds": int(rounds), "chair": chair, "verify": bool(verify)},
        "agent": chosen,
    }


def _scalar(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    raise TypeError(f"cannot render TOML scalar of type {type(value).__name__}")


def _render_value(value) -> str:
    if isinstance(value, list):
        return "[" + ", ".join(_scalar(v) for v in value) + "]"
    return _scalar(value)


# Stable key order for agent tables so output is deterministic and readable.
_AGENT_KEY_ORDER = ("name", "vendor", "command", "endpoint", "model", "extra_args")


def render_toml(config: dict) -> str:
    """Render a council config dict to ``council.toml`` text (minimal, typed).

    Handles exactly the value types this config uses (str/int/bool/list[str]).
    Empty/None values are omitted so a local agent (no ``command``/``extra_args``)
    stays clean.
    """
    lines = [
        "# Generated by `council init`. Edit freely — see docs/configuration.md",
        "# for the full schema (rounds, ci gate, context policy, diff handling).",
        "",
        "[council]",
    ]
    for key in ("rounds", "chair", "verify"):
        if key in config["council"]:
            lines.append(f"{key} = {_render_value(config['council'][key])}")
    lines.append("")

    for agent in config["agent"]:
        lines.append("[[agent]]")
        for key in _AGENT_KEY_ORDER:
            if key not in agent:
                continue
            value = agent[key]
            if value in (None, "", []):
                continue
            lines.append(f"{key} = {_render_value(value)}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"
